apiVersion: apps/v1
kind: Deployment
metadata:
  name: net5k8s-dep
spec:
  selector:
    matchLabels:
      app: net5k8s
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: net5k8s
        version: v1
    spec:
      containers:
      - name: net5k8s-cont
        image: net5k8s-img:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: net5k8s-svc
spec:
  selector:
    app: net5k8s
  type: LoadBalancer
  ports:
    - name: net5k8s-port
      port: 8002
      targetPort: 80